apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
<<<<<<< HEAD
          value: dns
=======
          value: env
        - name: REDIS_SLAVE_SERVICE_HOST
          value: redis-replica
>>>>>>> 42040a4f27bcf3e30815edba741d57b8ad34172e
        ports:
        - containerPort: 80
